### ISSUE TITLE
linux compilation broken

### ISSUE THREAD

**Issue by Laeeth** [jcd/deadcode#1]
this is with linux branch - similar if I use ldc2 (stable) or dmd (git head)

Laeeth.

extensions/language/d/completion.d(456,25): Error: no property 'connectTo' for type 'controls.texteditor.TextEditor', did you mean 'connect'?
extensions/language/d/dfmt.d(1100,69): Error: no property 'startLocation' for type 'const(StructInitializer)'
extensions/language/d/dfmt.d(1101,67): Error: no property 'endLocation' for type 'const(StructInitializer)'
extensions/unittests.d(50,2): Warning: statement is not reachable
extensions/unittests.d(52,2): Warning: statement is not reachable
libdeadcode/src/core/buffer.d(1005,17): Error: expression clamp(T1, T2, T3)(T1 val, T2 lower, T3 upper) of type void does not have a boolean value
libdeadcode/src/core/buffer.d(1014,17): Error: expression clamp(T1, T2, T3)(T1 val, T2 lower, T3 upper) of type void does not have a boolean value
Warning: setupRegistryEntry not implemented on linux
libdeadcode/src/gui/gui.d(356,55): Error: undefined identifier 'string'
libdeadcode/src/gui/gui.d(367,55): Error: undefined identifier 'string'
libdeadcode/src/gui/style/types.d(230,3): Error: template instance Rect!T template 'Rect' is not defined
libdeadcode/src/gui/text.d(605,12): Error: template instance gui.style.types.CSSScale.opBinary!"=" error instantiating
Warning: getCursorScreenPos not implemented
libdeadcode/src/util/string.d(24,57): Warning: use std.algorithm.reverse instead of .reverse property
libdeadcode/src/util/string.d(46,87): Warning: use std.algorithm.reverse instead of .reverse property
Warning: Missing checkDirForChanges on linux
libdeadcode/src/util/jsonx.d(337,21): Warning: use std.algorithm.sort instead of .sort property
/usr/include/dlang/dmd/std/container/array.d(837,20): Error: template std.exception.enforce cannot deduce function from argument types !()(RefCounted!(Payload, cast(RefCountedAutoInitialize)0)), candidates are:
/usr/include/dlang/dmd/std/exception.d(348,3):        std.exception.enforce(E : Throwable = Exception, T)(T value, lazy const(char)[] msg = null, string file = **FILE**, size_t line = **LINE**) if (is(typeof(()
{
if (!value)
{
}
}
)))
/usr/include/dlang/dmd/std/exception.d(362,3):        std.exception.enforce(T, string file, ulong line = **LINE**)(T value, lazy const(char)[] msg = null) if (is(typeof(()
{
if (!value)
{
}
}
)))
/usr/include/dlang/dmd/std/exception.d(376,3):        std.exception.enforce(T, Dg, string file = **FILE**, ulong line = **LINE**)(T value, scope Dg dg) if (isSomeFunction!Dg && is(typeof(dg())) && is(typeof(()
{
if (!value)
{
}
}
)))
/usr/include/dlang/dmd/std/exception.d(522,3):        std.exception.enforce(T)(T value, lazy Throwable ex)
/usr/include/dlang/dmd/std/container/array.d(872,45): Error: template instance std.container.array.Array!(Region).Array.insertBefore!(IntersectResult) error instantiating
libdeadcode/src/math/region.d(748,19):        instantiated from here: replace!(IntersectResult)
FAIL .dub/build/debug-debug-linux.posix-x86_64-dmd_2067-AE210F223871547ACD57CDFA1C1E1182/ ded-debug executable

**Comment by jcd** [comment]
Some of the errors makes immediately sense and I'll do a fix ASAP. A couple of them I'll have to look a but more into.

**Comment by jcd** [comment]
Now fixed against 2.066 (not pushed yet) but some of the error seems to be dmd git head only. I'll do a checkout of the dmd version and see if I can trigger the issues there.

**Comment by jcd** [comment]
Cannot build head of dmd right now (building druntime complains about _d_monitorenter is not nothrow?!). I pushed what was needed for the 2.066 build to go through that you can try out.

**Comment by Laeeth** [comment]
Tku

**Comment by jcd** [comment]
Just landed a large patchset from Ketmar for linux that could have fix this issue.

**Comment by jcd** [comment]
The linux build has been fine for some time now. Closing.
